######################################################################
# Name of the service and group that is responsible for it
######################################################################
serviceGroup=org.openlmis
serviceName=openlmis-dhis2-integration
serviceDescription=OpenLMIS DHIS2 Integration Service

######################################################################
# Current version of the service
# Only a Release Manager should update this
######################################################################
serviceVersion=1.2.0
